apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zly3ov6im-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.94063222-f67e-48ae-a597-8d8c44f683bb.prod.konfluxeaas.com/rhtap/rhtap-qe-java-springboot:c8e5ceb8b38146437166ce875d316981b68717c4@sha256:f0efe8826e938e1736542b105e1209132f176910063df5473b797299f1cec089
          name: container-image
